services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/ssl/la-doue:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - gateway
      - frontend
      - backend
      - auth-gateway
      - notifications
      - stock-management

  frontend:
    build: ./frontend
    expose:
      - "3000"

  backend:
    build: ./backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    expose:
      - "5000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    expose:
      - "27017"

  notifications:
    build: ./microservices/notifications
    expose:
      - "3001"

  stock-management:
    build: ./microservices/stock-management
    expose:
      - "3002"

  auth-gateway:
    build: ./microservices/auth-gateway
    expose:
      - "4001"

  gateway:
    build: ./gateway
    expose:
      - "8080"
    depends_on:
      - frontend
      - backend
      - notifications
      - stock-management
      - auth-gateway

volumes:
  mongo_data:

networks:
  default:
    name: exam1_network